// Automatically generated by flapigen
package com.example.docxgenerator.lib;
import androidx.annotation.NonNull;
/**
 * A simple android doc builder
 */
public final class AndroidDocBuilder {

    public AndroidDocBuilder() {
        mNativeObj = init();
    }
    private static native long init();
    /**
     * Add a text to the doc
     */
    public final void addText(@NonNull String text) {
        do_addText(mNativeObj, text);
    }
    private static native void do_addText(long self, @NonNull String text);
    /**
     * Add Image to the doc
     */
    public final void addImage(@NonNull String file, long width, long height) {
        do_addImage(mNativeObj, file, width, height);
    }
    private static native void do_addImage(long self, @NonNull String file, long width, long height);
    /**
     * Export the file
     */
    public final void generateDocx(@NonNull String file_name) {
        do_generateDocx(mNativeObj, file_name);
    }
    private static native void do_generateDocx(long self, @NonNull String file_name);

    public synchronized void delete() {
        if (mNativeObj != 0) {
            do_delete(mNativeObj);
            mNativeObj = 0;
       }
    }
    @Override
    protected void finalize() throws Throwable {
        try {
            delete();
        }
        finally {
             super.finalize();
        }
    }
    private static native void do_delete(long me);
    /*package*/ AndroidDocBuilder(InternalPointerMarker marker, long ptr) {
        assert marker == InternalPointerMarker.RAW_PTR;
        this.mNativeObj = ptr;
    }
    /*package*/ long mNativeObj;
}